# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: pygments

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'Mechanical Object'
tagline:          'Software like clockwork...'
description:      'Programming, algorithms, life etc.'
url:              'http://mechanicalobject.com'
baseurl:          ''

# Navigation
navigation:
- text: About
  url: /about/
- text: Resume
  url: /resume/
- text: Blog
  url: /blog/
- text: Tags
  url: /tags/
- text: Archive
  url : /archive/
- text: Search
  url: /search/
- text: Links
  url: /links/

# Author Details
author:         'Evrim'

#Social Media links (Use complete URL except for email)
dribbble:
email:
facebook:       
flickr:
github:         'https://github.com/mechanicalobject'
gplus:          
instagram:
pinterest:
linkedin:       'https://www.linkedin.com/in/senturkevrim/'
rss:
stackoverflow:  
twitter:        'https://twitter.com/mechanicalo'

# Google Analytics
gahandler: 'UA-57545242-2'

#if footersvg is 'true' the social media links will be shown top on the copy right in the footer
footersvg: 'true'

# Disqus
disqushandler: 'mechanicalobject'

# Blog Configurations
paginate: 10 # Posts per page on the blog index
paginate_path: '/blog/page:num'
destination: ./_site

# Custom vars
version:          0.9x beta 2 (custom)
